### ISSUE TITLE
New plot style: "surface-color"

### ISSUE THREAD

**Issue by coldfix** [visjs/vis-graph3d#97]
Hi,

I'd like to create a surface plot, where the color is determined by the "style" value, not the "z" coordinate, like this (modified basic example):

```
...
          var z = (Math.sin(x/50) * Math.cos(y/50) * 50 + 50);
          var c = (Math.sin(y/50) * 50 + 50);
          data.add({id:counter++, x: x, y: y, z: z, style: c});
...
```

![canvas](https://user-images.githubusercontent.com/1816880/75563402-96110900-5a4a-11ea-8f43-56669f765113.png)

I've tinkered a little with the implementation and this seems pretty easy to do. I'd be happy to make a PR. Do you have any thoughts on how this should be done, i.e.

- implement it as separate style, e.g. "surface-color", in analogy to "dot-color"
- add it to existing "surface" style and using `_getColorsColor(point)` in case of the current handling, e.g.
    - by autodetecting whether the "style" attribute is present or
    - by adding another switch (e.g. setting `surfaceColors: "style"`)

Personally, I'd prefer if e.g. `_getColorsColor` would use `point.value` for the color if present, otherwise fallback to `point.z`, and use this behaviour for all styles (so now technically, one wouldn't need the "dot-color" style anymore either, I believe. For that matter, I would even unify it with the "dot-size" style).

What do you think?

Best, Thomas

**Comment by Thomaash** [comment]
Hi @coldfix,

sounds great and contributions are deeply appreciated here. Personally I too would prefer overriding on a per point basis so that people can maybe highlight a few points or so and not just do everything manually or everything automatically.

Just one thing though could you elaborate a bit more on the API of this? Maybe create a draft PR and rewrite the docs in the way you want to implement it or something like that.

Thank you very much.
